#! /bin/bash
picom -b &
hsetroot -solid "#1e1e2e" &
xset r rate 120 60 &
# feh --bg-center ~/.images/windows-error.jpg &

emote &

while true; do
    cpu=$(cat /proc/stat | grep "cpu " | awk '{printf("%.2f\n", 100 - ($5+$6+$7+$8)*100/($1+$2+$3+$4+$5+$6+$7+$8))}')
    ram=$(free -m | awk 'NR==2{printf "%.2f%%\n", $3*100/$2 }')
    time=$(date "+%I:%M %p")

    status="$cpu% :: $ram :: $time"

    xsetroot -name "$status"

    sleep 5s
done &


exec dwm
