#! /bin/bash
picom -b &
hsetroot -solid "#1e1e2e" &
# feh --bg-center ~/.images/windows-error.jpg &

emote &

while true; do
    cpu=$(cat /proc/stat | grep "cpu " | awk '{printf("%.2f\n", 100 - ($5+$6+$7+$8)*100/($1+$2+$3+$4+$5+$6+$7+$8))}')
    ram=$(free -m | awk 'NR==2{printf "%.2f%%\n", $3*100/$2 }')
    time=$(date "+%I:%M %p")
    media=$(playerctl metadata title)
    media_display="${media:0:20}"${media:20:1:+...}

    status="$media_display :: $cpu% :: $ram :: $time"

    xsetroot -name "$status"

    sleep 5s
done &

exec dwm
