export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="trapd00r-catppuccin"

plugins=(git)

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

eval "$(zoxide init zsh)"

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ping='prettyping'

alias sudo="sudo "
alias ls="lsd -hN --group-directories-first --color=auto"
alias la="lsd -lahN --group-directories-first --color=auto"
alias ll="lsd -llhN --group-directories-first --color=auto"

function ff() {
    stamp="$(date +%s)"
    kitget --square -o "/tmp/kitget-$stamp"
    clear
    fastfetch --kitty "/tmp/kitget-$stamp" "$@"
    rm -f "/tmp/kitget-$stamp"
}

alias ga="git add"
alias gc="git commit -m"
alias gp="git push origin"
alias gb="git branch"
alias gpull="git pull origin"
alias gcherry="git cherry-pick -x"
alias gmain="if ! git checkout --track origin/main; then; if ! git checkout main; then git checkout master; fi ; fi"

function gclone() { git clone "$1" && cd "$(basename $1 .git)" }
function gcco() {
    local message="$1"
    shift

    for coauthor in "$@"; do
        local coauthors="$coauthors
Co-authored-by: $coauthor <${coauthor}@users.noreply.github.com>"
    done

    git commit -m "$message" -m "$coauthors"
}
function gupdate-branch { git fetch "$1" main && git merge "$1"/main }

alias db="distrobox"
alias cp="cp -i"

alias system-upgrade="rm -rf ~/.cache/paru && sudo pacman -Scc --noconfirm; paru -Scc --noconfirm; paru --noconfirm; paru -Qq | grep '\-git' | paru -S --noconfirm -; rustup update"
alias vencord-upgrade='sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"'

alias clipin="xsel --input --clipboard"
alias clipout="xsel --output --clipboard"

alias shred="shred -uvz"
function shreddir() { find "$1" -type f -exec shred -uvz {} \; rm -rf "$1" }

function b64 { echo "$1" | base64 }
function b64d { echo "$1" | base64 -d }

function nv() { nvim -u $HOME/.config/nvim/init.lua "$@"; echo -ne "\e[6 q" }

function command_not_found_handler() {
    echo -e "Command \e[91m$1\e[0m not found! \e[91mSTUPID! BONK!\e[0m OwO" >&2
    return 127
}

function cd() {
    { z "$@" 2>/dev/null && ls } || echo -e "Directory \e[91m$*\e[0m not found! \e[91mSTUPID! BONK!\e[0m OwO"
}

ff #; tmux ls
DWM_DIR=/home/adam/dwm
