user: "#cba6f7"
group: "#b4befe"
permission:
  read: "#94e2d5"
  write: "#f9e2af"
  exec: "#eba0ac"
  exec-sticky: "#cba6f7"
  no-access: "#a6adc8"
  octal: "#94e2d5"
  acl: "#94e2d5"
  context: "#b4befe"
date:
  hour-old: "#89b4fa"
  day-old: "#b4befe"
  older: "#cba6f7"
size:
  none: "#a6adc8"
  small: "#94e2d5"
  medium: "#f9e2af"
  large: "#eba0ac"
inode:
  valid: "#f5c2e7"
  invalid: "#a6adc8"
links:
  valid: "#f5c2e7"
  invalid: "#a6adc8"
tree-edge: "#bac2de"
git-status:
  default: "#cdd6f4"
  unmodified: "#a6adc8"
  ignored: "#a6adc8"
  new-in-index: "#94e2d5"
  new-in-workdir: "#94e2d5"
  typechange: "#f9e2af"
  deleted: "#eba0ac"
  renamed: "#94e2d5"
  modified: "#f9e2af"
  conflicted: "#eba0ac"
